FROM php:7.3-fpm-alpine as build

RUN \
  apk update && apk upgrade && apk add --no-cache $PHPIZE_DEPS \
  zlib-dev memcached-dev php7-pecl-memcached \ 
  libmemcached-libs libmemcached zlib-dev libmemcached-dev cyrus-sasl-dev wget

WORKDIR /tmp

RUN \
    wget https://pecl.php.net/get/memcached-3.1.5.tgz \
    && tar zxvf memcached-3.1.5.tgz \
    && ( \
         cd /tmp/memcached-3.1.5 \
        && /usr/local/bin/phpize /tmp/memcached-3.1.5   \
        && ./configure && make -j$(nproc) && make install \
        && docker-php-ext-enable memcached \
    ) \
    && rm memcached-3.1.5.tgz && rm -r memcached-3.1.5/
    
RUN \
  apk add --no-cache freetype-dev libjpeg-turbo-dev libpng-dev && \
  docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ \
  --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
  docker-php-ext-install -j$(($(nproc) + 2)) gd

RUN \
  apk add --no-cache bzip2-dev curl-dev libxml2-dev libzip-dev tidyhtml-dev libxslt-dev php7-iconv && \
  docker-php-ext-install -j$(($(nproc) + 2)) bcmath bz2 calendar ctype curl dba \
  mysqli opcache pcntl pdo pdo_mysql phar posix \
  session shmop soap sockets sysvmsg sysvsem sysvshm tidy tokenizer \
  xml xmlrpc xmlwriter xsl zip # iconv

FROM build as bitrix
COPY conf.d/php.ini /usr/local/etc/php/conf.d/php.ini
COPY conf.d/fpm.conf /usr/local/etc/php-fpm.d/www.conf

RUN \
  mkdir /var/www/bitrix && chown www-data: /var/www/bitrix && \
  mkdir /var/www/log/ && touch /var/www/log/php-error.log && \
  touch /var/www/log/fpm-access.log && \
  chown www-data: /var/www/log/

WORKDIR /var/www/bitrix
